"""
compile_brief.py

Assembles the final Markdown brief and plain-text email from summarized items.
"""

import os
from datetime import datetime, timezone
from typing import List

from summarize import SummarizedItem

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRIEFS_DIR = os.path.join(PROJECT_ROOT, "briefs")


def render_markdown(
    items: List[SummarizedItem],
    metadata: dict,
) -> str:
    date_str = metadata.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    n_sources = metadata.get("n_sources", 0)
    n_collected = metadata.get("n_collected", 0)
    n_included = metadata.get("n_included", 0)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append(f"# AI Intelligence Brief — Week of {date_str}")
    lines.append(f"")
    lines.append(f"> {n_sources} sources monitored | {n_collected} articles collected | {n_included} included | Generated {timestamp}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Top Stories (non-podcast)
    stories = [i for i in items if not i.is_podcast]
    if stories:
        lines.append("## Top Stories")
        lines.append("")
        for idx, item in enumerate(stories, 1):
            pub = item.published_date.strftime("%b %d") if item.published_date else ""
            multi = ""
            if item.supporting_sources:
                multi = f"  \n*Also covered by: {', '.join(item.supporting_sources)}*"

            lines.append(f"### {idx}. {item.headline}")
            lines.append(f"*{item.source_name} | Tier {item.tier} | {pub} | Score {item.relevance_score}/10*{multi}")
            lines.append("")
            if item.what_happened:
                lines.append(f"**What happened:** {item.what_happened}")
            if item.why_it_matters:
                lines.append(f"**Why it matters:** {item.why_it_matters}")
            if item.strategic_implication:
                lines.append(f"**Strategic implication:** {item.strategic_implication}")
            if item.url:
                lines.append(f"[Read more]({item.url})")
            lines.append("")
            lines.append("---")
            lines.append("")

    # Podcast Intelligence
    podcasts = [i for i in items if i.is_podcast]
    if podcasts:
        lines.append("## Podcast Intelligence")
        lines.append("")
        for pod in podcasts:
            lines.append(f"### {pod.headline}")
            lines.append(f"*{pod.source_name} | Tier 3*")
            lines.append("")
            for topic in pod.podcast_topics:
                t = topic.get("topic", "")
                discussed = topic.get("what_was_discussed", "")
                matters = topic.get("why_it_matters", "")
                lines.append(f"- **{t}:** {discussed} {matters}")
            lines.append("")
            if pod.podcast_takeaway:
                lines.append(f"**This week's takeaway:** {pod.podcast_takeaway}")
            lines.append("")
            lines.append("---")
            lines.append("")

    # Sources monitored table
    source_stats = metadata.get("source_stats", [])
    if source_stats:
        lines.append("## Sources Monitored")
        lines.append("")
        lines.append("| Source | Tier | Fetched | Included |")
        lines.append("|--------|------|---------|----------|")
        for s in source_stats:
            lines.append(f"| {s['name']} | {s['tier']} | {s['fetched']} | {s['included']} |")
        lines.append("")

    lines.append("---")
    lines.append("*Brief generated by AI Intelligence Pipeline.*")

    return "\n".join(lines)


def render_email_text(items: List[SummarizedItem], metadata: dict) -> str:
    date_str = metadata.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    n_included = metadata.get("n_included", 0)

    lines = []
    lines.append(f"AI INTELLIGENCE BRIEF — WEEK OF {date_str.upper()}")
    lines.append(f"{n_included} stories included this week")
    lines.append("")
    lines.append("=" * 60)
    lines.append("")

    stories = [i for i in items if not i.is_podcast]
    if stories:
        lines.append("TOP STORIES")
        lines.append("")
        for idx, item in enumerate(stories, 1):
            pub = item.published_date.strftime("%b %d") if item.published_date else ""
            multi = f" | Also: {', '.join(item.supporting_sources)}" if item.supporting_sources else ""
            lines.append(f"{idx}. {item.headline.upper()}")
            lines.append(f"   {item.source_name} | Tier {item.tier} | {pub}{multi}")
            lines.append("")
            if item.what_happened:
                lines.append(f"   What happened: {item.what_happened}")
            if item.why_it_matters:
                lines.append(f"   Why it matters: {item.why_it_matters}")
            if item.strategic_implication:
                lines.append(f"   Strategic implication: {item.strategic_implication}")
            if item.url:
                lines.append(f"   {item.url}")
            lines.append("")
            lines.append("-" * 60)
            lines.append("")

    podcasts = [i for i in items if i.is_podcast]
    if podcasts:
        lines.append("PODCAST INTELLIGENCE")
        lines.append("")
        for pod in podcasts:
            lines.append(f"{pod.headline.upper()}")
            lines.append(f"{pod.source_name}")
            lines.append("")
            for topic in pod.podcast_topics:
                t = topic.get("topic", "")
                discussed = topic.get("what_was_discussed", "")
                matters = topic.get("why_it_matters", "")
                lines.append(f"  - {t}: {discussed} {matters}")
            lines.append("")
            if pod.podcast_takeaway:
                lines.append(f"  This week's takeaway: {pod.podcast_takeaway}")
            lines.append("")

    return "\n".join(lines)


def write_brief(md_text: str, email_text: str, date_str: str) -> tuple:
    os.makedirs(BRIEFS_DIR, exist_ok=True)
    md_path = os.path.join(BRIEFS_DIR, f"{date_str}_brief.md")
    email_path = os.path.join(BRIEFS_DIR, f"{date_str}_brief_email.txt")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_text)
    with open(email_path, "w", encoding="utf-8") as f:
        f.write(email_text)
    return md_path, email_path
